#!/usr/bin/python

# wrapper for the node server code


import sys
import distutils.sysconfig

sys.path.append("%s/virtfactory" % distutils.sysconfig.get_python_lib())

from nodes import server


if __name__ == "__main__":
    server.main(sys.argv)
