#!/bin/bash
#
#
# virtfactory-wui       startup script for virtfactory-wui
#
# chkconfig: - 85 15
# description: virtfactory-wui is the web front end for virtfactory.
#              

VIRTFACTORY_DIR=/usr/share/virtfactory-wui
MONGREL_LOG=/var/log/virtfactory-wui/mongrel.log
MONGREL_PID=/var/run/virtfactory-wui/mongrel.pid
ADDR=127.0.0.1
RAILS_ENVIRONMENT=production
USER=virtfact
GROUP=virtfact
export RELATIVE_URL_ROOT=/sm
export Rails_GEM_VERSION=1.2.2

RETVAL=0

case "$1" in
    start)
      mongrel_rails start -c $VIRTFACTORY_DIR -l $MONGREL_LOG -P $MONGREL_PID -a $ADDR -e $RAILS_ENVIRONMENT --user $USER --group $GROUP -d
      RETVAL=$?
  ;;
    stop)
      mongrel_rails stop -c $VIRTFACTORY_DIR -P $MONGREL_PID
      RETVAL=$?
  ;;
    restart)
      mongrel_rails restart -c $VIRTFACTORY_DIR -P $MONGREL_PID
      RETVAL=$?
  ;;
    *)
      echo "Usage: virtfactory-wui {start|stop|restart}"
      exit 1
  ;;
esac      

exit $RETVAL
