#!/bin/bash
#
#
# virt-factory-wui       startup script for virt-factory-wui
#
# chkconfig: - 85 15
# description: virt-factory-wui is the web front end for virt-factory.
#              

VIRTFACTORY_DIR=/usr/share/virt-factory-wui
MONGREL_LOG=/var/log/virt-factory-wui/mongrel.log
MONGREL_PID=/var/run/virt-factory-wui/mongrel.pid
ADDR=127.0.0.1
RAILS_ENVIRONMENT=production
USER=virtfact
GROUP=virtfact
export RELATIVE_URL_ROOT=/vf
export Rails_GEM_VERSION=1.2.2

RETVAL=0

case "$1" in
    start)
      mongrel_rails start -c $VIRTFACTORY_DIR -l $MONGREL_LOG -P $MONGREL_PID -a $ADDR -e $RAILS_ENVIRONMENT --user $USER --group $GROUP -d
      RETVAL=$?
  ;;
    stop)
      mongrel_rails stop -c $VIRTFACTORY_DIR -P $MONGREL_PID
      RETVAL=$?
  ;;
    restart)
      if [ -f $MONGREL_PID ] ; then
	  mongrel_rails restart -c $VIRTFACTORY_DIR -P $MONGREL_PID
	  RETVAL=$?
      else
	  pkill mongrel_rails
	  mongrel_rails start -c $VIRTFACTORY_DIR -l $MONGREL_LOG -P $MONGREL_PID -a $ADDR -e $RAILS_ENVIRONMENT --user $USER --group $GROUP -d
	  RETVAL=$?
      fi
  ;;
    *)
      echo "Usage: virt-factory-wui {start|stop|restart}"
      exit 1
  ;;
esac      

exit $RETVAL
