# FIXME: eventually I want the build system to do this, but for now, it does not.
# run python codes.py to get more recent constants for this file, and replace
# the contents below.

ARCH_IA64 = 202
ARCH_X86 = 200
ARCH_X86_64 = 201
ERR_INTERNAL_ERROR = 5
ERR_INVALID_ARGUMENTS = 6
ERR_MISCONFIGURED = 10
ERR_NO_SUCH_OBJECT = 7
ERR_ORPHANED_OBJECT = 8
ERR_PASSWORD_INVALID = 4
ERR_SQL = 9
ERR_SUCCESS = 0
ERR_TOKEN_EXPIRED = 1
ERR_TOKEN_INVALID = 2
ERR_UNCAUGHT = 999
ERR_USER_INVALID = 3
IMAGE_IS_APPLIANCE_CONTAINER = 304
IMAGE_IS_BAREMETAL_APPLIANCE = 302
IMAGE_IS_EITHER_APPLIANCE = 303
IMAGE_IS_VIRT_APPLIANCE = 301
OP_ADD = 101
OP_DELETE = 103
OP_EDIT = 102
OP_GET = 106
OP_LIST = 104
OP_METHOD = 105
REASON_FORMAT = 405
REASON_ID = 402
REASON_NONE = 400
REASON_RANGE = 401
REASON_REQUIRED = 404
REASON_TYPE = 403
SUCCESS = 0

