# FIXME: eventually I want the build system to do this, but for now, it does not.
# run python codes.py to get more recent constants for this file, and replace
# the contents below.

ARCH_IA64 = 2
ARCH_X86 = 0
ARCH_X86_64 = 1
ERR_INTERNAL_ERROR = 5
ERR_INVALID_ARGUMENTS = 6
ERR_NO_SUCH_OBJECT = 7
ERR_ORPHANED_OBJECT = 8
ERR_PASSWORD_INVALID = 4
ERR_SQL = 9
ERR_SUCCESS = 0
ERR_TOKEN_EXPIRED = 1
ERR_TOKEN_INVALID = 2
ERR_UNCAUGHT = 999
ERR_USER_INVALID = 3
IMAGE_TYPE_APPLIANCE_CONTAINER = 4
IMAGE_TYPE_BAREMETAL_APPLIANCE = 2
IMAGE_TYPE_EITHER_APPLIANCE = 3
IMAGE_TYPE_VIRT_APPLIANCE = 1
MACHINE_TYPE_APPLIANCE_CONTAINER = 1
MACHINE_TYPE_BAREMETAL_APPLIANCE = 0
OP_ADD = 1
OP_DELETE = 3
OP_EDIT = 2
OP_GET = 6
OP_LIST = 4
OP_METHOD = 5
SUCCESS = 0


