#!/bin/sh
#
# virt-factory-node-server    virt-factory node server
#
# chkconfig: 345 99 99 
# description:  This is a web services daemon used by virt-factory
#           
#               See http://virt-factory.et.redhat.com
#
# processname: /usr/bin/cobbler_syslogd

# Sanity checks.
[ -x /usr/bin/vf_node_server ] || exit 0

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0


start() {
    echo -n $"Starting virt-factory node server : "
    if test -f /var/lock/subsys/vf_node_server ; then
        echo_failure
        echo
        return 1
    fi
 
    /usr/bin/vf_node_server --daemon
    RETVAL=$?
    echo_success
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/vf_node_server
    return $RETVAL
}


stop() {
    echo -n $"Stopping virt-factory node server: "
    if ! test -f /var/lock/subsys/vf_node_server ; then
        echo_failure
        echo
        return 1
    fi
    pkill vf_node_server
    RETVAL=$?
    rm /var/lock/subsys/vf_node_server
    echo_success
    echo
    return $RETVAL
}

mystatus() {
    if test -f /var/lock/subsys/vf_node_server ; then
        echo "vf_node_server is running..."
        return 0
    fi
    echo "vf_node_server is stopped"
    echo
    return 0
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        mystatus
        RETVAL=$?
        ;;
    restart)
        stop
        start
        ;;
    condrestart)
        if [ -f /var/lock/subsys/vf_node_server ]; then
            stop
            start
        fi
        ;;
    reload)
        echo "can't reload configuration, you have to restart it"
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
        ;;
esac
exit $RETVAL

