#!/bin/sh
#
# virt-factory-node-server    virt-factory node server
#
# chkconfig: 345 99 99 
# description:  This is a web services daemon used by virt-factory
#           
#               See http://virt-factory.et.redhat.com
#
# processname: /usr/bin/cobbler_syslogd

# Sanity checks.
[ -x /usr/bin/vf_node_server ] || exit 0

# Source function library.
. /etc/rc.d/init.d/functions

SERVICE=virt-factory-node-server
PROCESS=vf_node_server
CONFIG_ARGS=" "
BOOTUP=verbose

RETVAL=0

start() {
    echo -n $"Starting virt factory node server: "
    daemon --check $SERVICE $PROCESS --daemon $CONFIG_ARGS
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$SERVICE
    return $RETVAL
}

stop() {
    echo -n $"Stopping virt factory node server: "
    __pids_var_run $PROCESS
    killproc $PROCESS -INT
    RETVAL=$?
    for i in $(seq 1 15)
    do 
        if ! checkpid $pid; then
            if [ $RETVAL -eq 0 ]; then
                rm -f /var/lock/subsys/$SERVICE
                rm -f /var/run/$SERVICE.pid
            fi
	    return $RETVAL
	fi
	sleep 5
    done
    killproc $PROCESS
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        rm -f /var/lock/subsys/$SERVICE
        rm -f /var/run/$SERVICE.pid
    fi
    
}

restart() {
   stop
   start
}

# See how we were called.                                                                                                                                                   
case "$1" in
    start|stop|restart)
        $1
        ;;
    status)
        status $PROCESS
        RETVAL=$?
        ;;
    condrestart)
        [ -f /var/lock/subsys/$SERVICE ] && restart || :
        ;;
    reload)
        echo "can't reload configuration, you have to restart it"
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
        exit 1
        ;;
esac
exit $RETVAL




