#!/usr/bin/python
"""
Utility script which provides a list of puppet classes to puppetmasterd for a given node.

Copyright 2006, Red Hat, Inc
Michael DeHaan <mdehaan@redhat.com>
Scott Seago <sseago@redhat.com>
Adrian Likins <alikins@redhat.com>

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""

import sys
import distutils.sysconfig
import string
import xmlrpclib

sys.path.append("%s/virt-factory" % distutils.sysconfig.get_python_lib())


#--------------------------------------------------------------------------
class Server(xmlrpclib.ServerProxy):
    def __init__(self, url=None):
        xmlrpclib.ServerProxy.__init__(self, url)

      
def main(argv):
    """
    Start things up.
    """
    if len(argv) == 2:
        # if we ever support remote puppet servers, the URL will need
        # to be obtained differently
        server_url = "http://localhost:5150"
        token = "UNSET"
        server = Server(server_url)
        nodename = argv[1]
        rc = server.puppet_node_info(token, nodename)
        if rc[0] != 0:
            sys.exit(1)

        data = rc[1]["data"]
        if (data.has_key("parent")):
            print data["parent"]
        else:
            print
        print " ".join(data["puppet_classes"])
    else:
        print "Usage:" 
        print "sm_get_puppet_node.py nodename"
        sys.exit(1)

if __name__ == "__main__":
    main(sys.argv)



