#!/usr/bin/python


import sys
import distutils.sysconfig

sys.path.append("%s/virt-factory" % distutils.sysconfig.get_python_lib())

from server import gen_profile_stub

if __name__ == "__main__":
    gen_profile_stub.main(sys.argv)

