#!/usr/bin/python

"""
sm_import is a utility script which imports an profile profile from an
appliance definition file.

Profile profiles should be a self-contained tarball with the following directory structure:
	profile.xml  -- includes metadata needed for adding to SM database.
	manifests/profilename.pp  -- main puppet manifest for the
  	                             profile (should include the others)
	manifests/*.pp  -- other puppet manifests, can be named anything
	files/* -- includes data files referenced by manifests
 	templates/* -- includes templates referenced by manifests

Each execution of the sm_import tool will do the following:

	Use the XML data to insert a row into the profiles database IF it's not already imported
	Import the manifests to /var/lib/virt-factory/profiles/$profile-name/manifests/*
	Import the data files to /var/lib/virt-factory/profiles/$profile-name/files/*
	Import the templates files to /var/lib/virt-factory/profiles/$profile-name/templates/*
	Update the site-wide puppet manifest as necessary

NOTE: this can only be run after the initial "vf_server import", because
      distributions are needed in order to import profile profiles. 

Copyright 2007, Red Hat, Inc
Michael DeHaan <mdehaan@redhat.com>
Adrian Likins <alikins@redhat.com>
Scott Seago <sseago@redhat.com>

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""


import sys
import distutils.sysconfig

sys.path.append("%s/virt-factory" % distutils.sysconfig.get_python_lib())
sys.path.append("%s/virt-factory/server" % distutils.sysconfig.get_python_lib())

from modules import profileimporter

if __name__ == "__main__":
    profileimporter.main()

