#!/usr/bin/python


import sys
import distutils.sysconfig

sys.path.append("%s/virt-factory" % distutils.sysconfig.get_python_lib())
sys.path.append("%s/virt-factory/server" % distutils.sysconfig.get_python_lib())

from modules import nodecomm

if __name__ == "__main__":
    nodecomm.main(sys.argv)
