#!/usr/bin/python


import sys
import distutils.sysconfig

sys.path.append("%s/virt-factory" % distutils.sysconfig.get_python_lib())

from server import taskatron

if __name__ == "__main__":
    taskatron.main(sys.argv)

