#!/usr/bin/python


import sys
import distutils.sysconfig

sys.path.insert(0, "%s/virt-factory/ampm" % distutils.sysconfig.get_python_lib())

from client import ampm_cli
if __name__ == "__main__":

    ampm_cli.main()

