#!/usr/bin/python


import sys
import distutils.sysconfig

sys.path.append("%s/virt-factory" % distutils.sysconfig.get_python_lib())

from ampm import ampm_cli
if __name__ == "__main__":

    ampm_cli.main()

